### ISSUE TITLE
Error: not found: python2

### ISSUE THREAD

**Issue by biswajitpaul01** [julianpoma/aircraftdb#4]
Hi,

I am getting following error while installing node modules:

`[biswajit:angular]$npm install

> node-sass@4.7.2 install /var/www/html/lv/aircraftdb/angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall /var/www/html/lv/aircraftdb/angular/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.7.2 postinstall /var/www/html/lv/aircraftdb/angular/node_modules/node-sass
> node scripts/build.js

Building: /home/biswajit/.nvm/versions/node/v12.13.1/bin/node /var/www/html/lv/aircraftdb/angular/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/biswajit/.nvm/versions/node/v12.13.1/bin/node',
gyp verb cli   '/var/www/html/lv/aircraftdb/angular/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.6.2
gyp info using node@12.13.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/var/www/html/lv/aircraftdb/angular/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/html/lv/aircraftdb/angular/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/html/lv/aircraftdb/angular/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/html/lv/aircraftdb/angular/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/home/biswajit/.nvm/versions/node/v12.13.1/bin/node" "/var/www/html/lv/aircraftdb/angular/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/lv/aircraftdb/angular/node_modules/node-sass
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1012 packages from 1117 contributors and audited 5313 packages in 82.263s
found 196 vulnerabilities (55 low, 38 moderate, 100 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details`

**Comment by julianpoma** [comment]
Hi ! I just pushed a fix for this (a package upgrade). I got everything installed. Give it a try again

**Comment by biswajitpaul01** [comment]
@julianpoma 

Still no luck:

`
[angular]$ npm start

> angular@0.0.0 start /var/www/laravel/aircraftdb/angular
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2019-12-06T20:03:53.457Z                                                        
Hash: b9fd1f5d1c2fddb36d50
Time: 2070ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.93 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 636 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 639 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 853 kB [initial] [rendered]

ERROR in TypeError: _this.host.getOutputName is not a function
    at getOriginalName (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29595:32)
    at ReferenceTransformer.visitStringMap (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29640:43)
    at visitValue (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:427:24)
    at /var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:484:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:484:26)
    at ReferenceTransformer.visitStringMap (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29667:60)
    at visitValue (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:427:24)
    at /var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:484:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:484:26)
    at ReferenceTransformer.visitStringMap (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:29667:60)
    at visitValue (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:427:24)
    at /var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:484:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (/var/www/laravel/aircraftdb/angular/node_modules/@angular/compiler/bundles/compiler.umd.js:484:26)

webpack: Failed to compile.
`
